name: Update Bus Route Data

on:
  schedule:
    # 每天凌晨 8:00 UTC (台灣時間早上 4:00) 執行
    - cron: '0 20 * * *'
  workflow_dispatch:  # 允許手動觸發

jobs:
  update-taipei-data:
    name: Update Taipei Data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Install dependencies
        run: pip install dotenv

      - name: Pull latest changes
        run: git pull origin main

      - name: Run data update script for Taipei
        env:
          TAIPEI_URL: ${{ secrets.TAIPEI_URL }}
          NEWTAIPEI_URL: ${{ secrets.NEWTAIPEI_URL }}
        run: python ./backend/functions/update_data.py taipei  # 傳入 'taipei' 參數
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./backend/data/taipei/bus_routes.json
          git commit -m "Update Taipei bus route data" || echo "No changes to commit"
          git push

  update-newtaipei-data:
    name: Update Newtaipei Data
    runs-on: ubuntu-latest
    needs: update-taipei-data 
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Install dependencies
        run: pip install dotenv

      - name: Pull latest changes
        run: git pull origin main

      - name: Run data update script for Newtaipei
        env:
          TAIPEI_URL: ${{ secrets.TAIPEI_URL }}
          NEWTAIPEI_URL: ${{ secrets.NEWTAIPEI_URL }}
        # 這裡傳入 'newtaipei' 參數
        run: python ./backend/functions/update_data.py newtaipei

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./backend/data/newtaipei/bus_routes.json
          git commit -m "Update bus route data for Newtaipei" || echo "No changes to commit"
          git push
 